{% set name = "lark-parser" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/68/70/8f7ac67a67549796c091170863aee23d79b06c0dd5641c144e7d6d560ba8/lark_parser-0.10.0-py2.py3-none-any.whl
  sha256: f7044d3a4ad42c07e853da590727d5f1e5f9c36e5795bdeb05227fe0bace2344

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - lark
    - lark.parsers
    - lark.tools

about:
  home: https://github.com/erezsh/lark
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a modern parsing library

  description: |
    Lark is a modern general-purpose parsing library for Python.
    With Lark, you can parse any context-free grammar, efficiently, with very little code.
    Main Features:
     - Builds a parse-tree (AST) automagically, based on the structure of the grammar
     - Earley parser
        - Can parse all context-free grammars
        - Full support for ambiguous grammars
     - LALR(1) parser
        - Fast and light, competitive with PLY
        - Can generate a stand-alone parser
     - CYK parser, for highly ambiguous grammars
     - EBNF grammar
     - Unicode fully supported
     - Python 2 & 3 compatible
     - Automatic line & column tracking
     - Standard library of terminals (strings, numbers, names, etc.)
     - Import grammars from Nearley.js
     - Extensive test suite
     - And much more!
  doc_url: http://lark-parser.readthedocs.io/
  dev_url: https://github.com/erezsh/lark

extra:
  recipe-maintainers:
    - tarcisioe
    - mlin
